### PR TITLE
Fix gas price calculations in tracer

### LINKED ISSUE #2002: "insufficient funds for gas" error when doing debug_traceBlockByNumber on 0x108F49C
## Description
When running `debug_traceBlockByNumber` on block `0x108F49C` results in a `insufficient funds for gas` error

https://celoscan.io/block/17364124

## Current Behavior

Running the following request
```
{
    "method": "debug_traceBlockByNumber",
    "params": [
        "0x108F49C",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}
```

Results in this error
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "insufficient funds for gas * price + value + gatewayFee: address 0xBF4D711071Cd9c0402387DeCDD53d3babDb82Bf6 have 1702475464032708 want 1710879300000000"
    }
}
```

Celo client version: `v1.7.2`
OS: Linux

### PR DESCRIPTION
**Pull request by palango**
### Description

Fix the tracing module to correctly use the base fee when calculating
gas prices.

### Tested

Adds a regression test.

### Related issues

Resolves #2002

### CODE REVIEW

File: eth/tracers/api.go [hunk 1]
```diff
@@ -599,17 +613,21 @@ func (api *API) traceBlock(ctx context.Context, block *types.Block, config *Trac
 	}
 	blockCtx := core.NewEVMBlockContext(block.Header(), api.chainContext(ctx), nil)
 	blockHash := block.Hash()
+
+	isEspresso := api.backend.ChainConfig().IsEspresso(block.Number())
 	var sysCtx *core.SysContractCallCtx
-	if api.backend.ChainConfig().IsEspresso(block.Number()) {
-		sysCtx = core.NewSysContractCallCtx(block.Header(), statedb, api.backend)
+	if isEspresso {
+		// sysCtx = core.NewSysContractCallCtx(block.Header(), statedb, api.backend)
```
Comment (palango) [inline eth/tracers/api.go:620]: I'm not sure how to best set the mock here for the tests.

File: eth/tracers/api.go [hunk 2]
```diff
@@ -430,6 +434,14 @@ func (api *API) traceChain(ctx context.Context, start, end *types.Block, config
 	return sub, nil
 }
 
+func getBaseFee(isEspresso bool, sysCtx *core.SysContractCallCtx, tx *types.Transaction) *big.Int {
```
Comment (carterqw2) [inline eth/tracers/api.go:437]: Maybe it worth passing just the fee currency here, it woul make the function easier to test if we decide to do so.

Comment (palango) [reply eth/tracers/api.go]: Done

**Review by carterqw2 — APPROVED** [review]
Looks good!

File: eth/tracers/api_test.go [hunk 3]
```diff
@@ -601,6 +606,85 @@ func TestTraceBlock(t *testing.T) {
...
+
+	api := NewAPI(newTestBackend(t, 1, genesis, func(i int, b *core.BlockGen) {
+		// The block base fee is mocked to be 3
+		// Two transactions are build, so that the correct gas price is 5 (base fee of 3 + tip of 2), but the
+		// incorrect calculation leads to a gas price of 6.
+		// The account balance is chosen in a way that the second transaction won't be able to execute if the
+		// calculation is wrong.
+
+		tip := big.NewInt(2)
+		cap := big.NewInt(6)
```
Comment (gastonponti) [inline eth/tracers/api_test.go:648]: I would recommend to use something like:
```
gp := core.MockSysContractCallCtx().GetGasPriceMinimum(nil)
cap := gp.Add(gp, tip.Add(tip, big.NewInt(1)))
```
(didn't checked if it compiles, haha)
But, yes, the idea is to avoid that fixed number of 3. If that changes in the future, this test will still work, and behaviour as it should

File: eth/tracers/api_test.go [hunk 4]
```diff
@@ -601,6 +606,85 @@ func TestTraceBlock(t *testing.T) {
...
+
+		txdata1 := types.NewTx(&types.CeloDynamicFeeTx{
+			ChainID:   params.IstanbulEHFTestChainConfig.ChainID,
```
Comment (gastonponti) [inline eth/tracers/api_test.go:651]: As far as I understand, the core.BlockGen, it has the config. So you could access the same config you used to create it, which will avoid future updates if we change some of those chainConfigs

File: eth/tracers/api_test.go [hunk 5]
```diff
@@ -601,6 +606,85 @@ func TestTraceBlock(t *testing.T) {
...
+			Nonce:     0,
+			GasTipCap: tip,
+			GasFeeCap: cap,
+			Gas:       21_000,
+			To:        &accounts[1].addr,
+		})
+		tx1, _ := types.SignTx(
+			txdata1,
+			types.LatestSignerForChainID(params.IstanbulEHFTestChainConfig.ChainID),
```
Comment (gastonponti) [inline eth/tracers/api_test.go:660]: same

File: eth/tracers/api_test.go [hunk 6]
```diff
@@ -601,6 +606,85 @@ func TestTraceBlock(t *testing.T) {
...
+			accounts[0].key,
+		)
+		b.AddTx(tx1)
+
+		txdata2 := types.NewTx(&types.CeloDynamicFeeTx{
+			ChainID:   params.IstanbulEHFTestChainConfig.ChainID,
```
Comment (gastonponti) [inline eth/tracers/api_test.go:666]: same

File: eth/tracers/api_test.go [hunk 7]
```diff
@@ -601,6 +606,85 @@ func TestTraceBlock(t *testing.T) {
...
+			Nonce:     1,
+			GasTipCap: tip,
+			GasFeeCap: cap,
+			Gas:       21_000,
+			To:        &accounts[1].addr,
+		})
+		tx2, _ := types.SignTx(
+			txdata2,
+			types.LatestSignerForChainID(params.IstanbulEHFTestChainConfig.ChainID),
```
Comment (gastonponti) [inline eth/tracers/api_test.go:675]: same

**Review by gastonponti — COMMENTED** [review]
The majority are nits, and use the actual number that the mock will call for the gasPrice

File: eth/tracers/api_test.go (hunk 4 above)
Comment (palango) [reply eth/tracers/api_test.go:651]: Good point, I added a getter and accessed it from there.

File: eth/tracers/api_test.go (hunk 3 above)
Comment (palango) [reply eth/tracers/api_test.go:648]: This bigint handling is a massive pain. Operator overloading would be so nice here, one more reason to advocate for using rust. ;)

File: eth/tracers/api.go [hunk 8]
```diff
@@ -776,6 +789,14 @@ func (api *API) standardTraceBlockToFile(ctx context.Context, block *types.Block
 	return dumps, nil
 }
 
+func getBaseFee(isEspresso bool, sysCtx *core.SysContractCallCtx, feeCurrency *common.Address) *big.Int {
+	var baseFee *big.Int
+	if isEspresso && sysCtx != nil {
```
[the remark this answers is not in the document]
Comment (palango) [reply eth/tracers/api.go:794]: Good point. I wanted to be defensive here but I checked all callsites and this is unnecessary. Would the compiler optimize this away?

File: eth/tracers/api_test.go [hunk 9]
```diff
@@ -601,6 +606,85 @@ func TestTraceBlock(t *testing.T) {
...
...0871565b73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610865576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260148152602001807f73656e64657220776173206e6f74206f776e657200000000000000000000000081525060200191505060405180910390fd5b61086e816108bd565b50565b600080600160405180807f656970313936372e70726f78792e61646d696e000000000000000000000000008152506013019050604051809103902060001c0360001b9050805491505090565b600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff161415610960576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260118152602001807f6f776e65722063616e6e6f74206265203000000000000000000000000000000081525060200191505060405180910390fd5b6000600160405180807f656970313936372e70726f78792e61646d696e000000000000000000000000008152506013019050604051809103902060001c0360001b90508181558173ffffffffffffffffffffffffffffffffffffffff167f50146d0e3c60aa1d17a70635b05494f864e86144a2201275021014fbf08bafe260405160405180910390a2505056fea165627a7a72305820f4f741dbef8c566cb1690ae708b8ef1113bdb503225629cc1f9e86bd47efd1a40029")
```
[the remark this answers is not in the document]
Comment (palango) [reply eth/tracers/api_test.go:615]: There's also used in `TestEIP1559Transition`. Not sure if it's worth to extract it though.
