### PR TITLE
Fix data race: roundChangeTimer

### LINKED ISSUE #1587: Data race in istanbul/core (roundChangeTimer)
## Description

When running the test in #1564 with the  -race flag, the following data race was produced.
The round change timer is being read here:
https://github.com/celo-org/celo-blockchain/blob/02d31996e3e5db6f1b990163829b46708ae42407/consensus/istanbul/core/core.go#L702-L707

And constructed here by a different goroutine without any synchronisation:

https://github.com/celo-org/celo-blockchain/blob/02d31996e3e5db6f1b990163829b46708ae42407/consensus/istanbul/core/core.go#L736-L754

```
==================
WARNING: DATA RACE
Read at 0x00c0001a21d0 by goroutine 93:
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).stopRoundChangeTimer()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/core.go:703 +0x47
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).stopAllTimers()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/core.go:718 +0x46
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).Stop()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/handler.go:57 +0x3c
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).StopValidating()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:703 +0x16d
  github.com/celo-org/celo-blockchain/miner.(*worker).stop()
      /home/piersy/projects/celo-blockchain/miner/worker.go:216 +0xbb
  github.com/celo-org/celo-blockchain/miner.(*Miner).update()
      /home/piersy/projects/celo-blockchain/miner/miner.go:171 +0x67b

Previous write at 0x00c0001a21d0 by goroutine 154:
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).resetRoundChangeTimer()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/core.go:744 +0x253
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).startNewSequence()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/core.go:587 +0xa77
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).handleFinalCommitted()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/final_committed.go:22 +0x11d
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).handleEvents()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/handler.go:152 +0x406

Goroutine 93 (running) created at:
  github.com/celo-org/celo-blockchain/miner.New()
      /home/piersy/projects/celo-blockchain/miner/miner.go:75 +0x347
  github.com/celo-org/celo-blockchain/eth.New()
      /home/piersy/projects/celo-blockchain/eth/backend.go:236 +0x1a8b
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_util.go:52 +0x301
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:136 +0x9bb
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x411
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:482 +0xc8
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:131 +0x997
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:203 +0x25a
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:134 +0xfc
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:142 +0x1a7f
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:189 +0x109
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:225 +0xbb
  github.com/celo-org/celo-blockchain/ethdb/leveldb.New()
      /home/piersy/projects/celo-blockchain/ethdb/leveldb/leveldb.go:98 +0x3ba
  github.com/celo-org/celo-blockchain/core/rawdb.NewLevelDBDatabaseWithFreezer()
      /home/piersy/projects/celo-blockchain/core/rawdb/database.go:229 +0x84
  github.com/celo-org/celo-blockchain/node.(*ServiceContext).OpenDatabaseWithFreezer()
      /home/piersy/projects/celo-blockchain/node/service.go:71 +0x297
  github.com/celo-org/celo-blockchain/eth.New()
      /home/piersy/projects/celo-blockchain/eth/backend.go:141 +0x39a
  github.com/celo-org/celo-blockchain/test.(*Node).Start.func1()
      /home/piersy/projects/celo-blockchain/test/node.go:169 +0x4f
  github.com/celo-org/celo-blockchain/node.(*Node).Start()
      /home/piersy/projects/celo-blockchain/node/node.go:236 +0x813
  github.com/celo-org/celo-blockchain/test.(*Node).Start()
      /home/piersy/projects/celo-blockchain/test/node.go:175 +0x70a
  github.com/celo-org/celo-blockchain/test.NewNode()
      /home/piersy/projects/celo-blockchain/test/node.go:116 +0x83d
  github.com/celo-org/celo-blockchain/test.NewNetwork()
      /home/piersy/projects/celo-blockchain/test/node.go:368 +0x411
  github.com/celo-org/celo-blockchain/e2e_test_test.TestSendCelo()
      /home/piersy/projects/celo-blockchain/e2e_test/e2e_test.go:24 +0x78
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 154 (running) created at:
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).Start()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/handler.go:50 +0x38e
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).StartValidating()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:672 +0x261
  github.com/celo-org/celo-blockchain/miner.(*worker).start()
      /home/piersy/projects/celo-blockchain/miner/worker.go:206 +0x1a2
  github.com/celo-org/celo-blockchain/miner.(*Miner).update()
      /home/piersy/projects/celo-blockchain/miner/miner.go:166 +0x36e
==================

```

### PR DESCRIPTION
**Pull request by YoduYodu**
### Description

Add Mu to deal with data race around roundChangeTimer.

### Other changes

None

### Tested

`go test -race ./e2e_test` doesn't return data races on roundChangeTimer.

CI

### Related issues

- Fixes #1587 

### Backwards compatibility

Yes

### CODE REVIEW

File: mycelo/contract/gen_abis.go [hunk 1]
```diff
@@ -1100,7 +1100,7 @@ func init() {
       "stateMutability": "view",
       "type": "function"
     }
-  ]`)// Attestations ABI
```
Comment (trianglesphere) [inline mycelo/contract/gen_abis.go:1103]: Changes to this file seem to be accidentally included.

**Review by trianglesphere — APPROVED** [review]
