### PR TITLE
Fix load-bot failure with heavy load

### LINKED ISSUE #1455: mycelo load-bot breaks under heavy load
## Expected Behavior

The load-bot should not fail when submitting many transactions

## Current Behavior

The load bot fails after a few seconds with when a high tps is selected
```
./build/bin/mycelo load-bot --tps 100 loadtest
Error sending transaction: already known
Error sending transaction: failed to retrieve account nonce: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to retrieve account nonce: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: failed to estimate gas needed: context canceled
Error sending transaction: already known
```

## Steps to Reproduce Behavior

Start a network with mycelo and run a load bot with a high tps.

E.G `./build/bin/mycelo load-bot --tps 100 loadtest`

## System information

Run `geth version`
```
Celo
Version: 1.0.0-unstable
Git Commit: 42915a56d74073c33dce07ced6c3cf324990b242
Git Commit Date: 20210325
Architecture: amd64
Protocol Versions: [66 65 64]
Go Version: go1.13.8
Operating System: linux
GOPATH=/home/pierspowlesland/go
GOROOT=/usr/local/go
```

### PR DESCRIPTION
**Pull request by piersy**
### Description

This PR makes load-bot capable of consistently handling heavy load. Prior to this change heavy loads would result in load-bot failing due to resubmitting transactions with the same nonce. This was happening because we were calling `PendingNonceAt` to get the nonce for each transaction before sending it. `PendingNonceAt` looks into the transaction pool to discover the next viable nonce but there is no guarantee that the transaction pool will have updated with the latest sent transactions. This resulted in attempting to submit subsequent transactions with the same nonce.

### Other changes

Also fixed some race conditions in the load-bot.

### Tested

Was now able to successfully run the load-bot with heavy load (~100 tps)

### Related issues

- Fixes #1455 

### Backwards compatibility

These changes change no APIs or interfaces and so should be backwards compatible.

### CODE REVIEW

File: mycelo/loadbot/bot.go [hunk 1]
```diff
@@ -36,31 +36,30 @@ type Config struct {
...
-	sendIdx := uint(0)
-	nextSender := func() env.Account {
-		sendIdx++
-		return cfg.Accounts[sendIdx%uint(len(cfg.Accounts))]
-	}
-	clientIdx := uint(0)
-	nextClient := func() *ethclient.Client {
-		clientIdx++
-		return cfg.Clients[clientIdx%uint(len(cfg.Clients))]
+	// Set up nonces, we have to manage nonces becuase calling PendingNonceAt
```
Comment (trianglesphere) [inline mycelo/loadbot/bot.go:39]: nit: lint issue on misspell of because

**Review by trianglesphere — APPROVED** [review]
One fix for a lint otherwise nice catches on the nonce issue with more transactions than accounts and with the race condition on `nextSender` and `nextClient`

File: mycelo/loadbot/bot.go (hunk 1 above)
Comment (piersy) [reply mycelo/loadbot/bot.go:39]: Arrg, gets me every time :rage:
