### PR TITLE
Fix data race: istLogger

### LINKED ISSUE #1585: Data race in istanbul/core (roundState)
## Description

When running the test in #1564 with the -race flag, the following data race was produced.

The current round state is being written here:

https://github.com/celo-org/celo-blockchain/blob/02d31996e3e5db6f1b990163829b46708ae42407/consensus/istanbul/core/handler.go#L27-L35

and read without synchronisation from the peer handler goroutine.

```
==================
WARNING: DATA RACE
Write at 0x00c0001a2200 by goroutine 93:
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).Start()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/handler.go:35 +0xa7
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).StartValidating()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:672 +0x261
  github.com/celo-org/celo-blockchain/miner.(*worker).start()
      /home/piersy/projects/celo-blockchain/miner/worker.go:206 +0x1a2
  github.com/celo-org/celo-blockchain/miner.(*Miner).update()
      /home/piersy/projects/celo-blockchain/miner/miner.go:166 +0x36e

Previous read at 0x00c0001a2200 by goroutine 128:
  github.com/celo-org/celo-blockchain/consensus/istanbul/core.(*core).CurrentView()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/core/core.go:200 +0x4a
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.New.func1()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/backend.go:121 +0xc1
  github.com/celo-org/celo-blockchain/consensus/istanbul.(*istLogger).Trace()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/logger.go:43 +0x196
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).retrieveUncachedValidatorConnSet()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/backend.go:967 +0x803
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).updateCachedValidatorConnSet()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/backend.go:922 +0x418
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).RetrieveValidatorConnSet()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/backend.go:865 +0x2c7
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).RefreshValPeers()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/backend.go:814 +0x19a
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*validatorPeerHandler).thread.func1()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/peer_handler.go:81 +0xe4
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*validatorPeerHandler).thread()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/peer_handler.go:87 +0x132

Goroutine 93 (running) created at:
  github.com/celo-org/celo-blockchain/miner.New()
      /home/piersy/projects/celo-blockchain/miner/miner.go:75 +0x347
  github.com/celo-org/celo-blockchain/eth.New()
      /home/piersy/projects/celo-blockchain/eth/backend.go:236 +0x1a8b
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_util.go:52 +0x301
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:136 +0x9bb
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x411
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:482 +0xc8
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:131 +0x997
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:203 +0x25a
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:134 +0xfc
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:142 +0x1a7f
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:189 +0x109
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:225 +0xbb
  github.com/celo-org/celo-blockchain/ethdb/leveldb.New()
      /home/piersy/projects/celo-blockchain/ethdb/leveldb/leveldb.go:98 +0x3ba
  github.com/celo-org/celo-blockchain/core/rawdb.NewLevelDBDatabaseWithFreezer()
      /home/piersy/projects/celo-blockchain/core/rawdb/database.go:229 +0x84
  github.com/celo-org/celo-blockchain/node.(*ServiceContext).OpenDatabaseWithFreezer()
      /home/piersy/projects/celo-blockchain/node/service.go:71 +0x297
  github.com/celo-org/celo-blockchain/eth.New()
      /home/piersy/projects/celo-blockchain/eth/backend.go:141 +0x39a
  github.com/celo-org/celo-blockchain/test.(*Node).Start.func1()
      /home/piersy/projects/celo-blockchain/test/node.go:169 +0x4f
  github.com/celo-org/celo-blockchain/node.(*Node).Start()
      /home/piersy/projects/celo-blockchain/node/node.go:236 +0x813
  github.com/celo-org/celo-blockchain/test.(*Node).Start()
      /home/piersy/projects/celo-blockchain/test/node.go:175 +0x70a
  github.com/celo-org/celo-blockchain/test.NewNode()
      /home/piersy/projects/celo-blockchain/test/node.go:116 +0x83d
  github.com/celo-org/celo-blockchain/test.NewNetwork()
      /home/piersy/projects/celo-blockchain/test/node.go:368 +0x411
  github.com/celo-org/celo-blockchain/e2e_test_test.TestSendCelo()
      /home/piersy/projects/celo-blockchain/e2e_test/e2e_test.go:24 +0x78
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 128 (running) created at:
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*validatorPeerHandler).startThread()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/peer_handler.go:53 +0x114
  github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).StartAnnouncing()
      /home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:724 +0x1b0
  github.com/celo-org/celo-blockchain/eth.(*Ethereum).startAnnounce()
      /home/piersy/projects/celo-blockchain/eth/backend.go:515 +0x2fe
  github.com/celo-org/celo-blockchain/eth.(*Ethereum).Start()
      /home/piersy/projects/celo-blockchain/eth/backend.go:588 +0x294
  github.com/celo-org/celo-blockchain/node.(*Node).Start()
      /home/piersy/projects/celo-blockchain/node/node.go:265 +0x13eb
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_util.go:52 +0x301
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:136 +0x9bb
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x411
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:482 +0xc8
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:131 +0x997
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:203 +0x25a
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:134 +0xfc
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:142 +0x1a7f
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:189 +0x109
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:225 +0xbb
  github.com/celo-org/celo-blockchain/p2p/enode.newPersistentDB()
      /home/piersy/projects/celo-blockchain/p2p/enode/nodedb.go:96 +0xa9
  github.com/celo-org/celo-blockchain/p2p/enode.OpenDB()
      /home/piersy/projects/celo-blockchain/p2p/enode/nodedb.go:80 +0xa4
  github.com/celo-org/celo-blockchain/p2p.(*Server).setupLocalNode()
      /home/piersy/projects/celo-blockchain/p2p/server.go:588 +0x584
  github.com/celo-org/celo-blockchain/p2p.(*Server).Start()
      /home/piersy/projects/celo-blockchain/p2p/server.go:560 +0x832
  github.com/celo-org/celo-blockchain/node.(*Node).Start()
      /home/piersy/projects/celo-blockchain/node/node.go:253 +0x12aa
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_util.go:52 +0x301
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:136 +0x9bb
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x411
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:482 +0xc8
  github.com/syndtr/goleveldb/leveldb.openDB()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:131 +0x997
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:203 +0x25a
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xee
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x191
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:643 +0xa6
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/storage/file_storage.go:458 +0x309
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:134 +0xfc
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:142 +0x1a7f
  github.com/syndtr/goleveldb/leveldb.Open()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:189 +0x109
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /home/piersy/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:225 +0xbb
  github.com/celo-org/celo-blockchain/ethdb/leveldb.New()
      /home/piersy/projects/celo-blockchain/ethdb/leveldb/leveldb.go:98 +0x3ba
  github.com/celo-org/celo-blockchain/core/rawdb.NewLevelDBDatabaseWithFreezer()
      /home/piersy/projects/celo-blockchain/core/rawdb/database.go:229 +0x84
  github.com/celo-org/celo-blockchain/node.(*ServiceContext).OpenDatabaseWithFreezer()
      /home/piersy/projects/celo-blockchain/node/service.go:71 +0x297
  github.com/celo-org/celo-blockchain/eth.New()
      /home/piersy/projects/celo-blockchain/eth/backend.go:141 +0x39a
  github.com/celo-org/celo-blockchain/test.(*Node).Start.func1()
      /home/piersy/projects/celo-blockchain/test/node.go:169 +0x4f
  github.com/celo-org/celo-blockchain/node.(*Node).Start()
      /home/piersy/projects/celo-blockchain/node/node.go:236 +0x813
  github.com/celo-org/celo-blockchain/test.(*Node).Start()
      /home/piersy/projects/celo-blockchain/test/node.go:175 +0x70a
  github.com/celo-org/celo-blockchain/test.NewNode()
      /home/piersy/projects/celo-blockchain/test/node.go:116 +0x83d
  github.com/celo-org/celo-blockchain/test.NewNetwork()
      /home/piersy/projects/celo-blockchain/test/node.go:368 +0x411
  github.com/celo-org/celo-blockchain/e2e_test_test.TestSendCelo()
      /home/piersy/projects/celo-blockchain/e2e_test/e2e_test.go:24 +0x78
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
==================

```

### PR DESCRIPTION
**Pull request by YoduYodu**
### Description

There are two loggers in two engines, one in backend engine under `consensus/istanbul/backend`, another in core engine under `consensus/istanbul/core`.
They both use the same logger [implementation](https://github.com/celo-org/celo-blockchain/blob/e613f7c82d8226c7a4adf97437bcb9a0e0117e13/consensus/istanbul/logger.go#L32), which reads core.roundState.currentView() for its Trace, Debug, while backend.startValidating() is trying to initialized it. It's not a thread safe variable, thus caused race condition.

This PR lets the backend engine use its own logger, some reasoning:
* `core.roundState` is initialized when started, and set to nil when stopped. These are the only writes. All other operations on it are reads. So it doesn't make sense to add lock/unlock to every operations.
* backend engine should be decoupled from core engine.
* core engine itself is merely a debug filter that upgrade the message to Info when round > 0.

### Other changes

Fixed some comments, syntax

### Tested

CI

### Related issues

- Fixes #1585 

### Backwards compatibility

Yes

### CODE REVIEW

File: consensus/istanbul/logger.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func (l *istLogger) Trace(msg string, ctx ...interface{}) {
 }
 
 func (l *istLogger) Debug(msg string, ctx ...interface{}) {
-	// If the current round > 1, then upgrade this message to Info
+	// If the current round > 0, then upgrade this message to Info
 	if l.round != nil && l.round() != nil && l.round().Cmp(common.Big1) > 0 {
```
Comment (piersy) [inline consensus/istanbul/logger.go:52]: The check is comparing `round()` to `common.Big1`

File: consensus/istanbul/core/handler.go [hunk 2]
```diff
@@ -93,9 +93,7 @@ func (c *core) unsubscribeEvents() {
 
 func (c *core) handleEvents() {
 	// Clear state
-	defer func() {
-		c.handlerWg.Done()
-	}()
+	defer c.handlerWg.Done()
```
Comment (piersy) [inline consensus/istanbul/core/handler.go:96]: nice :)

File: consensus/istanbul/backend/backend.go [hunk 3]
```diff
@@ -149,20 +149,10 @@ func New(config *istanbul.Config, db ethdb.Database) consensus.Istanbul {
...
 
-	backend.logger = istanbul.NewIstLogger(
-		func() *big.Int {
-			if backend.core != nil && backend.core.CurrentView() != nil {
-				return backend.core.CurrentView().Round
-			}
-			return common.Big0
-		},
-	)
-
```
Comment (piersy) [inline consensus/istanbul/backend/backend.go:165]: This is going to change the logging functionality, previously when this was in use if round 2 was reached then Trace and Debug messages would be output at the Info level. Now this is not the case.

The original PR that introduced the IstLogger doesn't provide any explanation of why the change was needed.

I would actually be in favour of removing the IstLogger altogether since it seems like the kind of thing that would confuse node operators (why did my logging output jut increase massively and why are the logging levels different from what I'm used to seeing?)

@oneeman @mcortesi would you be able to provide any insight here?

Comment (oneeman) [reply consensus/istanbul/backend/backend.go:165]: I'm not familiar with it.  My guess would be that the idea was that if there's a round change it may indicate things going wrong (though it can also happen due to the proposer being offline) and that you'd want more logging in that case.  But I don't know whether it has proven to be useful in the end, and at least I wasn't even aware of it.

Comment (trianglesphere) [reply consensus/istanbul/backend/backend.go:165]: that's the theory. Another nice part of the istLogger is the auto population of the round state information (round, sequence, desiredRound, state, etc)

Comment (piersy) [reply consensus/istanbul/backend/backend.go:165]: I spoke with @timmoreton and yeah the theory was that it'd be useful to have the extra logging if there was a round change because something went wrong. But this can also be achieved on a per validator basis by increasing the log verbosity through the console using the debug api and given that he didn't see any reason this couldn't be removed.

 So I'm in favour of removing it because that fixes this immediate problem, and puts control back in the hands of validators, allowing them to increase the logging level if they need it but not forcing it upon them.

Comment (piersy) [reply consensus/istanbul/backend/backend.go:165]: @trianglesphere Could you point me to the "auto population of the round state information" ? I can't see anything relating to that in the ist logger code.

Comment (trianglesphere) [reply consensus/istanbul/backend/backend.go:165]: @piersy It's actually `(c *core) newLogger(ctx ...interface{}) log.Logger` which does the auto-population. My bad as I got confused between that and the istLogger.

**Review by trianglesphere — APPROVED** [review]
lgtm
