### PR TITLE
Fix panic on lightest mode client when requesting a block with unknown hash

### LINKED ISSUE #1627: Light client panics on `eth_getBlockByHash` with an incorrect block hash
## Expected Behavior

RPC method calls shouldn't crash the node

## Current Behavior

When running in light client mode (sync mode "light" or "lightest"), a panic can be triggered through `eth_getBlockByHash` when the hash specified doesn't correspond to an actual block.  You can also trigger it via `eth_getBlock` this way (since `eth_getBlock` uses `eth_getBlockByHash` if given a hash).

## Steps to Reproduce Behavior

1. Run a node in light client mode (e.g. with `--syncmode lightest`)
2. Wait until it's connected to some peers and started syncing (the panic doesn't happen if you have no peers at the time of the RPC method call)
3. Call `eth_getBlockByHash` by RPC or `eth.getBlockByHash` from the `geth attach` console, with a hash for a block that doesn't exist, e.g. `0x8888888888888888888888888888888888888888888888888888888888888888`:
```
> eth.getBlockByHash("0x8888888888888888888888888888888888888888888888888888888888888888", false)
```
4. The node will panic

The panic is not recovered from, even though this is a method handler, because it happens in a different goroutine since handling the RPC request involves firing off an ODR request and the panic is from the goroutine responsible for handling the response rather than the goroutine that handles the RPC request.

## Logs

```
panic: runtime error: index out of range [-1]

goroutine 248 [running]:
github.com/celo-org/celo-blockchain/core.(*HeaderChain).ValidateHeaderChain(0xc0001c4510, 0x5e761e8, 0x0, 0x0, 0x1, 0xc009fb1600, 0x0, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/core/headerchain.go:282 +0xc5c
github.com/celo-org/celo-blockchain/light.(*LightChain).InsertHeaderChain(0xc000494400, 0x5e761e8, 0x0, 0x0, 0x1, 0x2a848caa00, 0x0, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/light/lightchain.go:402 +0x105
github.com/celo-org/celo-blockchain/les.(*clientHandler).handleMsg(0xc008d2d2c0, 0xc009f8e8c0, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/les/client_handler.go:324 +0xba5
github.com/celo-org/celo-blockchain/les.(*clientHandler).handle(0xc008d2d2c0, 0xc009f8e8c0, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/les/client_handler.go:241 +0x792
github.com/celo-org/celo-blockchain/les.(*clientHandler).runPeer(0xc008d2d2c0, 0x3, 0xc00030c0e0, 0x54e39e0, 0xc0006e9f40, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/les/client_handler.go:169 +0x158
github.com/celo-org/celo-blockchain/les.(*lesCommons).makeProtocols.func1(0xc00030c0e0, 0x54e39e0, 0xc0006e9f40, 0xc0001a2340, 0xc0004d2d20)
	github.com/celo-org/celo-blockchain/les/commons.go:94 +0x4c
github.com/celo-org/celo-blockchain/p2p.(*Peer).startProtocols.func1(0xc00030c0e0, 0xc0006e9f40, 0x54e39e0, 0xc0006e9f40)
	github.com/celo-org/celo-blockchain/p2p/peer.go:439 +0x98
created by github.com/celo-org/celo-blockchain/p2p.(*Peer).startProtocols
	github.com/celo-org/celo-blockchain/p2p/peer.go:437 +0x205
```

## System information

Happens with the latest master, but also with v1.3.2, v1.2.x and v1.1.x.  Didn't test with v1.0.x.

```
Celo
Version: 1.4.0-unstable
Git Commit: e7edbe3e23e2dc078755039c288dd9faf22f0c3f
Git Commit Date: 20210715
Architecture: amd64
Protocol Versions: [66]
Go Version: go1.16.4
Operating System: darwin
```

But also reproduced with v1.3.2 and v1.2.5.

### PR DESCRIPTION
**Pull request by oneeman**
### Description

Previously, if you use `eth_getBlock` on a lightest mode client, and specify a hash that doesn't correspond to a block, the entire client would crash due to a panic in client_handler.go.  This PR fixes that panic, and makes getting a block by an unknown hash return "unknown block", which is the desired behavior and also what you get when you request a block by an unknown number (a number that is higher than the last block's number).

This requires modifying the `HeaderRequest` ODR request type to properly work when receiving a response with no headers.  This PR modifies it to accept such responses if the request was by hash, but not if it was by number.  This opens the door for a malicious LES server to fool a light client into thinking there is no block with this hash, when in fact there is.  However, it's simpler and seems preferable to the alternative of querying all one's peers in case some of them are malicious this way, and only returning "unknown block" after querying all of them.  **It's also preferable to the current status quo of malicious nodes being able to crash a lightest mode client by returning an empty response.**  Note, too, that requesting the header by hash is only done through the RPC API and is not a common use-pattern by light client users.

Another possibility would be, if you get an empty result, to then ask another node or another two nodes, to reduce the probability of being fooled.  But this PR takes the more minimal approach for now, and we can open up a separate issue about making such a change.

### Tested

Manual testing using `geth attach`

### Related issues

- Fixes #1627

### Backwards compatibility

See above in the description for how the behavior changes.

### CODE REVIEW

File: les/odr_requests.go [hunk 1]
```diff
@@ -164,7 +169,15 @@ func (r *HeaderRequest) Validate(db ethdb.Database, msg *Msg) error {
...
 	}
 	headers := msg.Obj.([]*types.Header)
-	if len(headers) != 1 {
+	if len(headers) == 0 && r.isByHash() {
+		// For requests by number, we only send to peers for which we know the block number
+		// is within the range of what they have, so if they don't send us the header we reject
+		// the response and try other peers.
+		// However, for requests by hash, we have no way of knowing ahead of time whether the peer
+		// should have it or not (e.g. what if there is no such block?).  So we need to accept
+		// 'no match' as a valid response, to avoid ODR endlessly trying to send to different peers.
```
Comment (piersy) [inline les/odr_requests.go:178]: What does ODR stand for?

File: les/odr_requests.go [hunk 2]
```diff
@@ -164,7 +169,15 @@ func (r *HeaderRequest) Validate(db ethdb.Database, msg *Msg) error {
 		return errInvalidMessageType
 	}
 	headers := msg.Obj.([]*types.Header)
-	if len(headers) != 1 {
+	if len(headers) == 0 && r.isByHash() {
+		// For requests by number, we only send to peers for which we know the block number
```
Comment (piersy) [inline les/odr_requests.go:173]: How do we know what range of blocks a peer has?

File: light/lightchain.go [hunk 3]
```diff
@@ -298,7 +298,9 @@ func (lc *LightChain) GetBlockByHash(ctx context.Context, hash common.Hash) (*ty
 	number := lc.hc.GetBlockNumber(hash)
 	if number == nil {
 		header, err := GetHeaderByHash(ctx, lc.odr, hash)
-		if err != nil {
+		// Header may be nil, indicating the hash doesn't match any known blocks,
+		// which is a valid response to the ODR request.
+		if err != nil || header == nil {
 			return nil, errors.New("unknown block")
```
Comment (piersy) [inline light/lightchain.go:304]: I think it would be helpful to include the hash in this error string.

File: les/odr_requests.go (hunk 1 above)
Comment (oneeman) [reply les/odr_requests.go:178]: On-demand retrieval: https://github.com/celo-org/celo-blockchain/blob/1188111ac106a92c6c9d89c5ff3da265b404a161/light/lightchain.go#L17

Though I've also heard "on-demand requests" as the more guessable meaning.

File: les/odr_requests.go (hunk 2 above)
Comment (oneeman) [reply les/odr_requests.go:173]: It's based on information we maintain about the peer: https://github.com/celo-org/celo-blockchain/blob/1188111ac106a92c6c9d89c5ff3da265b404a161/les/peer.go#L600-L622 .

File: light/lightchain.go (hunk 3 above)
Comment (oneeman) [reply light/lightchain.go:304]: I'd hesitate about lumping this in here.  If you search for "unknown block" in the codebase we return it from several places, including as https://github.com/celo-org/celo-blockchain/blob/1188111ac106a92c6c9d89c5ff3da265b404a161/consensus/istanbul/backend/engine.go#L63 .  In the case of users making API requests, they should know the hash they requested.  And as far as having it in the logs, it may be part of a bigger conversation worth having about having more information logged from API requests vs having the logs be done by the client or nginx gateway.  Regardless I wouldn't favor adding it to just this one.

**Review by mcortesi — APPROVED** [review]
LGTM
